# Generated by Django 4.2.21 on 2026-02-17 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServicePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "tagline",
                    models.CharField(blank=True, help_text="Short marketing blurb", max_length=200),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "price_monthly",
                    models.DecimalField(
                        decimal_places=2, help_text="Price in USD per month", max_digits=8
                    ),
                ),
                (
                    "price_annual",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual price (leave blank if same as monthly × 12)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "billing_period",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("annual", "Annual")],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_price_id_monthly",
                    models.CharField(
                        blank=True,
                        help_text="Stripe Price ID for the monthly price object",
                        max_length=100,
                    ),
                ),
                (
                    "stripe_price_id_annual",
                    models.CharField(
                        blank=True,
                        help_text="Stripe Price ID for the annual price object",
                        max_length=100,
                    ),
                ),
                (
                    "tier_key",
                    models.CharField(
                        blank=True,
                        help_text="Matches subscription_tier value on User (e.g. starter, professional)",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_featured",
                    models.BooleanField(default=False, help_text="Highlight on pricing page"),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Service Plan",
                "verbose_name_plural": "Service Plans",
                "ordering": ["sort_order", "price_monthly"],
            },
        ),
        migrations.CreateModel(
            name="PlanFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                (
                    "is_included",
                    models.BooleanField(default=True, help_text="✓ included vs ✗ not included"),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="services.serviceplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan Feature",
                "verbose_name_plural": "Plan Features",
                "ordering": ["sort_order"],
            },
        ),
    ]
