# Generated by Django 6.0.2 on 2026-02-18 01:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_provisioningjob_vpsinstance"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentevent",
            options={
                "ordering": ["-received_at"],
                "verbose_name": "Payment Event",
                "verbose_name_plural": "Payment Events",
            },
        ),
        migrations.AddField(
            model_name="paymentevent",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="paymentevent",
            name="received_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="paymentevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "Received"),
                    ("processing", "Processing"),
                    ("processed", "Processed"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                ],
                db_index=True,
                default="received",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="paymentevent",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
