# Generated by Django 6.0.2 on 2026-02-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_payment_event_status_tracking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentevent",
            name="event_type",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
